# Github actions yaml file to check the installation of the package

# check on push, and once a month
on:
  push:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  create_job_matrix:
    name: Generate matrix of install builds
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: latest

      - name: Install jsonlite
        run: Rscript -e 'install.packages("jsonlite")'

      - name: Set build matrix
        run: echo "matrix={\"config\":$(Rscript .github/gen_matrix.R)}" >> $GITHUB_OUTPUT

  check:
    name: check output
    needs: create_job_matrix
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Check matrix
        run: echo ${{ needs.create_job_matrix.outputs.matrix }}

  install:
    needs: create_job_matrix

    runs-on: ${{ matrix.config.os }}-${{ matrix.config.v }}

    name: ${{ matrix.config.os }} ${{ matrix.config.v }} (${{ matrix.config.r }})

    strategy:
      matrix: ${{ fromJson(needs.create_job_matrix.outputs.matrix) }}

    # set RSPM in env
    env:
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install dependencies
        run: |
          sudo apt-get install -y builds/$(cat ${{ matrix.config.os }}/${{ matrix.config.v }}/dependencies.txt)

      - name: Install iNZight with `make`
        run: make

      - name: Check UI loads
        uses: coactions/setup-xvfb@v1
        with:
          run: ./inzight
