# Github actions yaml file to check the installation of the package

# check on push, and once a month
on:
  push:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  install:
    runs-on: ${{ matrix.config.os }}-${{ matrix.config.v }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      matrix:
        config:
          - { os: ubuntu, v: 22.04, r: release }

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      # install deps from {os}/{version}/dependencies.txt
      - name: Install dependencies
        run: |
          sudo apt-get install -y $(cat ${{ matrix.config.os }}/${{ matrix.config.v }}/dependencies.txt)
