# Github actions yaml file to check the installation of the package

# check on push, and once a month
on:
  push:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  install:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      matrix:
        config:
          - { os: ubuntu-22.04, r: release }

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      # get dependencies from dependencies.yaml
      - name: Install dependencies
        run: |
          apt-get install -y r-base libgtk2.0-dev xorg-dev
